### PR TITLE
use lazy_static to initialize conversion tables

### PR DESCRIPTION
**Pull request by hops**
First of all: awesome project! Funny enough I would have started something similar in the near future. So thank you for saving me some work ;)

I noticed in every call to `mutate()` the conversion tables are recreated using `make_converts()`. They will always be the same so we can initialize ones and reuse them. This saves a lot of allocation and moving memory around.
As these are dynamically built using `make_converts()` and therefore not known at compile time we can't use static here. Luckily the lazy_static crate exists.

In my benchmark, using a cleartext list with 50,000 lines and a wordlist with 1,000,000 lines this patch is roughly three times faster than before.

```
$ time ./target/release/rulesfinder --hashcat -n 50 --minsize=5 -t8 -p cleartext -w wordlist > before_patch.rules
[ETA: 00:00:00] ████████████████ 47794/47794 - 1274131 fragments inserted
[ETA: 00:00:00] ████████████████ 2950/2950 - 6520 rules retained

real	3m19.519s
user	26m18.740s
sys	0m8.450s

$ time ./target/release/rulesfinder --hashcat -n 50 --minsize=5 -t8 -p cleartext -w wordlist > after_patch.rules
[ETA: 00:00:00] ████████████████ 47794/47794 - 1274504 fragments inserted
[ETA: 00:00:00] ████████████████ 2950/2950 - 6520 rules retained

real	1m5.899s
user	8m35.118s
sys	0m5.773s

$ sha256sum *.rules
6fb9b28e1d3004bf4d25d5a3c75f45654129909fcebc95140d1f238cd4ef956d  after_patch.rules
6fb9b28e1d3004bf4d25d5a3c75f45654129909fcebc95140d1f238cd4ef956d  before_patch.rules
```
I'm not super familiar with Rust namespaces so there might be a better solution than initializing them in src/main.rs.

### CODE REVIEW

**Comment by SimonMarechal** [comment]
Oh wow, that is some bad mistake you caught here! Thanks a lot, I did not know about `lazy_static`.

**Comment by SimonMarechal** [comment]
This doesn't make any difference performance-wise for me ... which is very strange?

**Comment by hops** [comment]
That's very strange indeed... Maybe it's not noticeable with certain combinations of wordlist/cleartext lists?
I reran my benchmark and still see the same result as I reported in the pull request.
The machine running this is using a i7-6700k. Maybe a more modern CPU isn't as impacted by this? But at this point I'm simply guessing.

**Comment by SimonMarechal** [comment]
It looks like it should give a very noticeable speed boost. What version of the rust compiler do you use?

**Comment by hops** [comment]
Latest stable (1.43.1) on Linux

**Comment by SimonMarechal** [comment]
This is so weird :) Anyway, thanks a lot again!

**Comment by hops** [comment]
I tested it with a bigger cleartext list (500,000 lines). The speedup isn't 3x but still 1.5x (6min vs. 4min). So I guess with larger lists the speedup isn't as noticeable anymore as more cycles are spent on other parts of the code.

**Pull request merged**
